//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportskiCentar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public int ShoppingCartID { get; set; }
        public int OrdinalNum { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
